### ISSUE TITLE
Pillow 7.0.0 Removed deprecated PILLOW_VERSION

### ISSUE THREAD

**Issue by woodongwong** [avinashpaliwal/Super-SloMo#68]
**Describe the bug**
Pillow 7.0.0 Removed deprecated PILLOW_VERSION
https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#700-2020-01-02

**Interpolated results/error output**
```
Traceback (most recent call last):
  File "video_to_slomo.py", line 9, in <module>
    import torchvision.transforms as transforms
  File "/root/miniconda3/lib/python3.7/site-packages/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/root/miniconda3/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/root/miniconda3/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/root/miniconda3/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/root/miniconda3/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/root/miniconda3/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/root/miniconda3/lib/python3.7/site-packages/PIL/__init__.py)
```

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Device Used: CPU
 - Setup Info: PyTorch 0.4.1, Python 3.7, Pillow 7.0.0, ...

**Comment by hugovk** [comment]
This has been fixed in the new [torchvision 0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0).

Please upgrade: `pip install torchvision>=0.5.0"`
